// core-free/src/hr.react.tsx
import './hr.css';

import React, { useState, useEffect, useMemo, useRef } from 'react';
import { RevoGrid, BasePlugin, type PluginProviders } from '@revolist/react-datagrid';
import { getHRColumnsCount, getHRData, getHRVisibleColumnsCount, HR_OPTIONS } from './sys-data/hr.data';
import type { HRGenerationProgress } from './sys-data/hr.data.generator';
import { getBaseHRColumns, getExtraHRColumns, HR_COLOR_BY_AGE, withHRShortDate } from './sys-data/hr.columns';
import { createHRColorSelectColumnType, renderHrColorPill } from './hr-color-select';
import { getHRLoadingDigits, getHRProgressPercent } from './hr-loading';
import { getInitialHRTheme, HR_THEME_DEFINITIONS, HR_THEME_OPTIONS } from './hr-themes';
import DateCol from '@revolist/revogrid-column-date';
import NumeralCol from '@revolist/revogrid-column-numeral';
import SelectCol from '@revolist/revogrid-column-select';
import {
  createHRPerformanceMonitor,
  createInitialHRPerformanceState,
  formatDuration,
  formatFrameRate,
  formatMemory,
  getHRMetricTooltipId,
  HR_PERFORMANCE_METRICS,
  type HRPerformanceMetricKey,
  type HRPerformanceMonitor,
} from './hr-performance';
import {
  applyHRWorkspaceToColumns,
  createHRWorkspaceController,
  getHRWorkspaceRowCount,
  HR_DEFAULT_ROW_COUNT,
  loadHRWorkspace,
  type HRWorkspaceController,
  type HRWorkspaceState,
} from './hr-workspace';

interface HRDemoProps {
  isDark?: boolean;
}

function HRMetricLabel({ metric }: { metric: HRPerformanceMetricKey }) {
  const definition = HR_PERFORMANCE_METRICS[metric];
  const tooltipId = getHRMetricTooltipId(metric);
  return (
    <div className="hr-performance-label">
      <span>{definition.label}</span>
      <span className="hr-metric-help">
        <button
          type="button"
          className="hr-metric-help-trigger"
          aria-label={`About ${definition.label}`}
          aria-describedby={tooltipId}
        >?</button>
        <span className="hr-metric-tooltip" id={tooltipId} role="tooltip">{definition.description}</span>
      </span>
    </div>
  );
}

export const HRDemo: React.FC<HRDemoProps> = ({ isDark }) => {
  const [workspaceState, setWorkspaceState] = useState<HRWorkspaceState>(() => loadHRWorkspace());
  const [workspaceStatus, setWorkspaceStatus] = useState(() => Object.keys(loadHRWorkspace()).length ? 'Saved locally' : 'View not saved');
  const [rows, setRows] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [loadingLabel, setLoadingLabel] = useState('Preparing rows…');
  const [currentSize, setCurrentSize] = useState(() => getHRWorkspaceRowCount(loadHRWorkspace(), HR_OPTIONS.map(option => option.value)));
  const [selectedTheme, setSelectedTheme] = useState(() => {
    const saved = loadHRWorkspace().theme;
    return HR_THEME_OPTIONS.some(option => option.value === saved) ? saved! : getInitialHRTheme(isDark);
  });
  const [columnTypes, setColumnTypes] = useState<any>({});
  const [progress, setProgress] = useState<HRGenerationProgress>({ loaded: 0, total: 100 });
  const [performanceState, setPerformanceState] = useState(createInitialHRPerformanceState);
  const activeController = useRef<AbortController | null>(null);
  const gridRef = useRef<HTMLRevoGridElement>(null);
  const performanceMonitor = useRef<HRPerformanceMonitor | null>(null);
  const workspaceController = useRef<HRWorkspaceController | null>(null);

  const plugins = useMemo(() => [
    class HRPlugin extends BasePlugin {
      constructor(r: HTMLRevoGridElement, p: PluginProviders) {
        super(r, p);
        this.addEventListener('rowdragstart', (e) => {
          if (e.detail.model) {
            e.detail.text = e.detail.model['name'];
          }
        });
      }
    },
  ], []);
  
  const loadData = async (size: number) => {
    activeController.current?.abort();
    const controller = new AbortController();
    activeController.current = controller;
    setLoading(true);
    setLoadingLabel(`Preparing ${size.toLocaleString()} rows…`);
    setProgress({ loaded: 0, total: size });
    const preparationStartedAt = performance.now();
    try {
      const data = await getHRData(size, {
        signal: controller.signal,
        onProgress: setProgress,
      });
      performanceMonitor.current?.setPreparationResult(
        performance.now() - preparationStartedAt,
        size,
        getHRVisibleColumnsCount(size),
      );
      setLoadingLabel('Rendering RevoGrid…');
      if (performanceMonitor.current) {
        await performanceMonitor.current.measureGridUpdate(() => setRows(data));
      } else {
        setRows(data);
      }
    } catch (error) {
      if (!(error instanceof DOMException && error.name === 'AbortError')) {
        throw error;
      }
    } finally {
      if (activeController.current === controller) {
        setLoading(false);
        activeController.current = null;
      }
    }
  };

  useEffect(() => {
    if (gridRef.current) {
      performanceMonitor.current = createHRPerformanceMonitor(gridRef.current, setPerformanceState);
      workspaceController.current = createHRWorkspaceController(
        gridRef.current,
        workspaceState,
        () => setWorkspaceStatus('Unsaved changes'),
      );
    }
    const init = () => {
      setColumnTypes({
        date: withHRShortDate(new DateCol()),
        number: new NumeralCol(),
        select: new SelectCol(),
        colorSelect: createHRColorSelectColumnType(SelectCol)
      });
      
      loadData(currentSize);
    };
    init();
    return () => {
      activeController.current?.abort();
      performanceMonitor.current?.destroy();
      performanceMonitor.current = null;
      workspaceController.current?.destroy();
      workspaceController.current = null;
    };
  }, []);

  useEffect(() => {
    if (!workspaceState.theme) {
      setSelectedTheme(getInitialHRTheme(isDark));
    }
  }, [isDark, workspaceState.theme]);

  const columns = useMemo(() => {
    const dropdownSource = Array.from(new Set(rows.map(r => r.company))).filter(Boolean) as string[];
    const baseCols = getBaseHRColumns(dropdownSource);

    // RevoGrid cell templates must return Stencil/RevoGrid VNodes via `h`.
    const nameCol = (baseCols[0] as any).children[1];
    nameCol.cellTemplate = (h: any, props: any) =>
      h('div', { class: 'flex items-center' }, [
        h('div', { class: 'hr-avatar' }, [
          h('img', {
            src: props.model.avatar,
            alt: props.value,
            class: 'w-full h-full object-cover',
          }),
        ]),
        props.value,
      ]);

    const personalGroup = baseCols[1] as any;
    const ageCol = personalGroup.children[0];
    ageCol.cellTemplate = (h: any, props: any) => [
      h('i', {
        class: 'hr-circle',
        style: { borderColor: HR_COLOR_BY_AGE(props.value) },
      }),
      props.value,
    ];

    const eyesCol = personalGroup.children[2];
    eyesCol.cellTemplate = (h: any, props: any) =>
      renderHrColorPill(h, props.value);

    return applyHRWorkspaceToColumns(
      [...baseCols, ...getExtraHRColumns(getHRColumnsCount(currentSize))],
      workspaceState,
    );
  }, [rows, currentSize, workspaceState]);

  const onSizeChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const nextSize = parseInt(e.target.value, 10);
    setCurrentSize(nextSize);
    setWorkspaceStatus('Unsaved changes');
    loadData(nextSize);
  };

  const saveView = async () => {
    if (!workspaceController.current) return;
    const saved = await workspaceController.current.save({ rowCount: currentSize, theme: selectedTheme });
    setWorkspaceState(saved);
    setWorkspaceStatus('Saved locally');
  };

  const resetView = () => {
    workspaceController.current?.clear();
    setWorkspaceState({});
    setCurrentSize(HR_DEFAULT_ROW_COUNT);
    setSelectedTheme(getInitialHRTheme(isDark));
    setWorkspaceStatus('View reset');
    if (gridRef.current) {
      gridRef.current.filter = { collection: {} };
      gridRef.current.sorting = undefined;
    }
    loadData(HR_DEFAULT_ROW_COUNT);
  };

  const progressPercent = getHRProgressPercent(progress);
  const loadingDigits = getHRLoadingDigits(progress);

  return (
    <div className="hr-demo grow h-full flex flex-col">
      <div className="hr-toolbar">
        <span className="text-sm font-medium">Data Source</span>
        <select
          className="hr-select"
          value={currentSize}
          onChange={onSizeChange}
          disabled={loading}
        >
          {HR_OPTIONS.map(opt => (
            <option key={opt.value} value={opt.value}>
              {opt.label}
            </option>
          ))}
        </select>
        <span className="text-sm font-medium">Theme</span>
        <select
          className="hr-select"
          value={selectedTheme}
          onChange={event => {
            setSelectedTheme(event.target.value);
            setWorkspaceStatus('Unsaved changes');
          }}
        >
          {HR_THEME_OPTIONS.map(option => (
            <option key={option.value} value={option.value}>
              {option.label}
            </option>
          ))}
        </select>
        <button type="button" className="hr-button" onClick={saveView}>Save view</button>
        <button type="button" className="hr-button hr-button-secondary" onClick={resetView}>Reset view</button>
        <span className="hr-workspace-status">{workspaceStatus}</span>
        {loading && <div className="text-sm opacity-50 animate-pulse ml-2">{loadingLabel}</div>}
      </div>

      <div className="hr-grid-wrapper flex-1 min-h-0">
        <RevoGrid
          ref={gridRef}
          className="hr-scale-grid grow h-full w-full"
          style={{ height: '100%', width: '100%' }}
          theme={selectedTheme}
          themeDefinitions={HR_THEME_DEFINITIONS}
          source={rows}
          columns={columns}
          columnTypes={columnTypes}
          plugins={plugins}
          filter={workspaceState.filter ?? true}
          sorting={workspaceState.sorting}
          range={true}
          resize={true}
          rowHeaders={true}
          hideAttribution={true}
          canMoveColumns={true}
          rowSize={36}
        />
        {loading && (
          <div className="hr-loading-overlay" aria-live="polite">
            <div className="hr-loading-counter" aria-label={`${progressPercent} percent complete`}>
              <div className="hr-loading-counter-line">
                {loadingDigits.map((digit, index) => (
                  <span
                    key={`${digit}-${index}-${progressPercent}`}
                    className="hr-loading-counter-digit"
                  >
                    {digit}
                  </span>
                ))}
                <span className="hr-loading-counter-symbol">%</span>
              </div>
            </div>
            <div className="hr-loading-label">{loadingLabel}</div>
          </div>
        )}
      </div>

      <section className="hr-performance" aria-label="Browser performance metrics">
        <div className="hr-performance-heading">
          <strong>Performance</strong>
          <span>Measured live in this browser</span>
        </div>
        <div className="hr-performance-metric">
          <HRMetricLabel metric="preparation" />
          <strong>{formatDuration(performanceState.preparationTime)}</strong>
        </div>
        <div className="hr-performance-metric">
          <HRMetricLabel metric="grid" />
          <strong>{formatDuration(performanceState.gridRenderTime)}</strong>
        </div>
        <div className="hr-performance-metric">
          <HRMetricLabel metric="scroll" />
          <strong>{formatFrameRate(performanceState.scrollFps)}</strong>
        </div>
        <div className="hr-performance-metric">
          <HRMetricLabel metric="memory" />
          <strong>{formatMemory(performanceState.memoryUsage?.usedJSHeapSize)}</strong>
        </div>
        <div className="hr-performance-metric">
          <HRMetricLabel metric="dataset" />
          <strong>{performanceState.rowCount.toLocaleString()} × {performanceState.columnCount}</strong>
        </div>
      </section>
    </div>
  );
};

export default HRDemo;

// core-free/src/hr.vue
<template>
  <div class="hr-demo">
    <div class="hr-toolbar">
      <span class="text-sm font-medium">Data Source</span>
      <select
        class="hr-select"
        v-model="currentSize"
        @change="onSizeChange"
        :disabled="loading"
      >
        <option v-for="opt in options" :key="opt.value" :value="opt.value">
          {{ opt.label }}
        </option>
      </select>
      <span class="text-sm font-medium">Theme</span>
      <select class="hr-select" v-model="selectedTheme" @change="workspaceStatus = 'Unsaved changes'">
        <option v-for="opt in themeOptions" :key="opt.value" :value="opt.value">
          {{ opt.label }}
        </option>
      </select>
      <button type="button" class="hr-button" @click="saveView">Save view</button>
      <button type="button" class="hr-button hr-button-secondary" @click="resetView">Reset view</button>
      <span class="hr-workspace-status">{{ workspaceStatus }}</span>
      <div v-if="loading" class="text-sm opacity-50 animate-pulse ml-2">{{ loadingLabel }}</div>
    </div>

    <div class="hr-grid-wrapper">
      <VGrid
        ref="gridRef"
        class="hr-scale-grid grow h-full w-full"
        style="height: 100%; width: 100%"
        :theme="gridTheme"
        :theme-definitions="themeDefinitions"
        :source="rows"
        :columns="columns"
        :column-types="columnTypes"
        :filter="workspaceState.filter ?? true"
        :sorting="workspaceState.sorting"
        :plugins="plugins"
        range
        resize
        row-headers
        hide-attribution
        can-move-columns
        :row-size="36"
      />
      <div v-if="loading" class="hr-loading-overlay" aria-live="polite">
        <div class="hr-loading-counter" :aria-label="`${progressPercent} percent complete`">
          <div class="hr-loading-counter-line">
            <span
              v-for="(digit, index) in loadingDigits"
              :key="`${digit}-${index}-${progressPercent}`"
              class="hr-loading-counter-digit"
            >
              {{ digit }}
            </span>
            <span class="hr-loading-counter-symbol">%</span>
          </div>
        </div>
        <div class="hr-loading-label">{{ loadingLabel }}</div>
      </div>
    </div>

    <section class="hr-performance" aria-label="Browser performance metrics">
      <div class="hr-performance-heading">
        <strong>Performance</strong>
        <span>Measured live in this browser</span>
      </div>
      <div class="hr-performance-metric">
        <div class="hr-performance-label">
          <span>{{ metricDefinitions.preparation.label }}</span>
          <span class="hr-metric-help">
            <button type="button" class="hr-metric-help-trigger" :aria-label="`About ${metricDefinitions.preparation.label}`" :aria-describedby="getHRMetricTooltipId('preparation')">?</button>
            <span class="hr-metric-tooltip" :id="getHRMetricTooltipId('preparation')" role="tooltip">{{ metricDefinitions.preparation.description }}</span>
          </span>
        </div>
        <strong>{{ formatDuration(performanceState.preparationTime) }}</strong>
      </div>
      <div class="hr-performance-metric">
        <div class="hr-performance-label">
          <span>{{ metricDefinitions.grid.label }}</span>
          <span class="hr-metric-help">
            <button type="button" class="hr-metric-help-trigger" :aria-label="`About ${metricDefinitions.grid.label}`" :aria-describedby="getHRMetricTooltipId('grid')">?</button>
            <span class="hr-metric-tooltip" :id="getHRMetricTooltipId('grid')" role="tooltip">{{ metricDefinitions.grid.description }}</span>
          </span>
        </div>
        <strong>{{ formatDuration(performanceState.gridRenderTime) }}</strong>
      </div>
      <div class="hr-performance-metric">
        <div class="hr-performance-label">
          <span>{{ metricDefinitions.scroll.label }}</span>
          <span class="hr-metric-help">
            <button type="button" class="hr-metric-help-trigger" :aria-label="`About ${metricDefinitions.scroll.label}`" :aria-describedby="getHRMetricTooltipId('scroll')">?</button>
            <span class="hr-metric-tooltip" :id="getHRMetricTooltipId('scroll')" role="tooltip">{{ metricDefinitions.scroll.description }}</span>
          </span>
        </div>
        <strong>{{ formatFrameRate(performanceState.scrollFps) }}</strong>
      </div>
      <div class="hr-performance-metric">
        <div class="hr-performance-label">
          <span>{{ metricDefinitions.memory.label }}</span>
          <span class="hr-metric-help">
            <button type="button" class="hr-metric-help-trigger" :aria-label="`About ${metricDefinitions.memory.label}`" :aria-describedby="getHRMetricTooltipId('memory')">?</button>
            <span class="hr-metric-tooltip" :id="getHRMetricTooltipId('memory')" role="tooltip">{{ metricDefinitions.memory.description }}</span>
          </span>
        </div>
        <strong>{{ formatMemory(performanceState.memoryUsage?.usedJSHeapSize) }}</strong>
      </div>
      <div class="hr-performance-metric">
        <div class="hr-performance-label">
          <span>{{ metricDefinitions.dataset.label }}</span>
          <span class="hr-metric-help">
            <button type="button" class="hr-metric-help-trigger" :aria-label="`About ${metricDefinitions.dataset.label}`" :aria-describedby="getHRMetricTooltipId('dataset')">?</button>
            <span class="hr-metric-tooltip" :id="getHRMetricTooltipId('dataset')" role="tooltip">{{ metricDefinitions.dataset.description }}</span>
          </span>
        </div>
        <strong>{{ performanceState.rowCount.toLocaleString() }} × {{ performanceState.columnCount }}</strong>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed, onBeforeUnmount, nextTick } from 'vue';
import { VGrid, type ColumnGrouping, type ColumnRegular, BasePlugin, type PluginProviders } from '@revolist/vue3-datagrid';
import { getHRColumnsCount, getHRData, getHRVisibleColumnsCount, HR_OPTIONS } from './sys-data/hr.data';
import type { HRGenerationProgress } from './sys-data/hr.data.generator';
import { getBaseHRColumns, getExtraHRColumns, HR_COLOR_BY_AGE, withHRShortDate } from './sys-data/hr.columns';
import { currentTheme, observeCurrentTheme } from '../../composables/useRandomData';
import { createHRColorSelectColumnType, renderHrColorPill } from './hr-color-select';
import { getHRLoadingDigits, getHRProgressPercent } from './hr-loading';
import { getInitialHRTheme, HR_THEME_DEFINITIONS, HR_THEME_OPTIONS } from './hr-themes';
import {
  createHRPerformanceMonitor,
  createInitialHRPerformanceState,
  formatDuration,
  formatFrameRate,
  formatMemory,
  getHRMetricTooltipId,
  HR_PERFORMANCE_METRICS,
  type HRPerformanceMonitor,
} from './hr-performance';
import {
  applyHRWorkspaceToColumns,
  createHRWorkspaceController,
  getHRWorkspaceRowCount,
  HR_DEFAULT_ROW_COUNT,
  loadHRWorkspace,
  type HRWorkspaceController,
  type HRWorkspaceState,
} from './hr-workspace';
import './hr.css';

const props = defineProps<{
  isDark?: boolean;
}>();

const pageIsDark = ref(currentTheme().isDark());
const initialWorkspace = loadHRWorkspace();
const workspaceState = ref<HRWorkspaceState>(initialWorkspace);
const workspaceStatus = ref(Object.keys(initialWorkspace).length ? 'Saved locally' : 'View not saved');
const loading = ref(false);
const loadingLabel = ref('Preparing rows…');
const currentSize = ref(getHRWorkspaceRowCount(initialWorkspace, HR_OPTIONS.map(option => option.value)));
const options = HR_OPTIONS;
const themeOptions = HR_THEME_OPTIONS;
const themeDefinitions = HR_THEME_DEFINITIONS;
const rows = ref<any[]>([]);
const gridRef = ref<HTMLRevoGridElement | { $el: HTMLRevoGridElement } | null>(null);
const performanceState = ref(createInitialHRPerformanceState());
const metricDefinitions = HR_PERFORMANCE_METRICS;
const progress = ref<HRGenerationProgress>({ loaded: 0, total: currentSize.value });
const defaultTheme = () => getInitialHRTheme(props.isDark === true || pageIsDark.value);
const selectedTheme = ref(HR_THEME_OPTIONS.some(option => option.value === initialWorkspace.theme)
  ? initialWorkspace.theme!
  : defaultTheme());
const gridTheme = computed(() => selectedTheme.value);
const progressPercent = computed(() => getHRProgressPercent(progress.value));
const loadingDigits = computed(() => getHRLoadingDigits(progress.value));
let activeController: AbortController | undefined;
let disconnectTheme: (() => void) | undefined;
let performanceMonitor: HRPerformanceMonitor | undefined;
let workspaceController: HRWorkspaceController | undefined;

// column types
const columnTypes = ref<any>({});

// custom plugin for row drag text
const plugins = [
  class HRPlugin extends BasePlugin {
    constructor(r: HTMLRevoGridElement, p: PluginProviders) {
      super(r, p);
      this.addEventListener('rowdragstart', (e) => {
        if (e.detail.model) {
          e.detail.text = e.detail.model['name'];
        }
      });
    }
  },
];

const columns = computed(() => {
  const dropdownSource: string[] = Array.from(new Set(rows.value.map(r => r.company))).filter(Boolean);
  const baseCols = getBaseHRColumns(dropdownSource);

  // Apply Vue-specific templates
  const nameCol = (baseCols[0] as ColumnGrouping).children[1] as ColumnRegular;
  nameCol.cellTemplate = (h, props) =>
    h('span', { class: 'flex items-center' }, [
      h('span', { class: 'hr-avatar' }, [
        h('img', { src: props.model.avatar, alt: props.value, class: 'w-full h-full object-cover' })
      ]),
      props.value
    ]);

  const personalGroup = baseCols[1] as ColumnGrouping;
  const ageCol = personalGroup.children[0] as ColumnRegular;
  ageCol.cellTemplate = (h, props) => [
    h('i', {
      class: 'hr-circle',
      style: { borderColor: HR_COLOR_BY_AGE(props.value) }
    }),
    props.value
  ];

  const eyesCol = personalGroup.children[2] as ColumnRegular;
  eyesCol.cellTemplate = (h, props) =>
    renderHrColorPill(h, props.value);

  return applyHRWorkspaceToColumns(
    [...baseCols, ...getExtraHRColumns(getHRColumnsCount(currentSize.value))],
    workspaceState.value,
  );
});

async function loadData() {
  activeController?.abort();
  const controller = new AbortController();
  activeController = controller;
  loading.value = true;
  loadingLabel.value = `Preparing ${currentSize.value.toLocaleString()} rows…`;
  progress.value = { loaded: 0, total: currentSize.value };
  const preparationStartedAt = performance.now();
  try {
    const data = await getHRData(currentSize.value, {
      signal: controller.signal,
      onProgress: nextProgress => {
        progress.value = nextProgress;
      },
    });
    performanceMonitor?.setPreparationResult(
      performance.now() - preparationStartedAt,
      currentSize.value,
      getHRVisibleColumnsCount(currentSize.value),
    );
    loadingLabel.value = 'Rendering RevoGrid…';
    if (performanceMonitor) {
      await performanceMonitor.measureGridUpdate(() => {
        rows.value = data;
      });
    } else {
      rows.value = data;
    }
  } catch (error) {
    if (!(error instanceof DOMException && error.name === 'AbortError')) {
      throw error;
    }
  } finally {
    if (activeController === controller) {
      loading.value = false;
      activeController = undefined;
    }
  }
}

function onSizeChange() {
  workspaceStatus.value = 'Unsaved changes';
  loadData();
}

async function saveView() {
  if (!workspaceController) return;
  workspaceState.value = await workspaceController.save({
    rowCount: currentSize.value,
    theme: selectedTheme.value,
  });
  workspaceStatus.value = 'Saved locally';
}

async function resetView() {
  workspaceController?.clear();
  workspaceState.value = {};
  currentSize.value = HR_DEFAULT_ROW_COUNT;
  selectedTheme.value = defaultTheme();
  workspaceStatus.value = 'View reset';
  await nextTick();
  const gridValue = gridRef.value;
  const grid = gridValue && ('$el' in gridValue ? gridValue.$el : gridValue);
  if (grid) {
    grid.filter = { collection: {} };
    grid.sorting = undefined;
  }
  loadData();
}

onMounted(async () => {
  disconnectTheme = observeCurrentTheme((isDark) => {
    pageIsDark.value = isDark;
    if (!workspaceState.value.theme) {
      selectedTheme.value = getInitialHRTheme(props.isDark === true || isDark);
    }
  });

  // Load column types in parallel with data to optimize initial load time
  const [DateCol, NumeralCol, SelectCol] = await Promise.all([
    import('@revolist/revogrid-column-date'),
    import('@revolist/revogrid-column-numeral'),
    import('@revolist/revogrid-column-select')
  ]);

  columnTypes.value = {
    date: withHRShortDate(new DateCol.default()),
    number: new NumeralCol.default(),
    select: new SelectCol.default(),
    colorSelect: createHRColorSelectColumnType(SelectCol.default)
  };

  await nextTick();
  const gridValue = gridRef.value;
  const grid = gridValue && ('$el' in gridValue ? gridValue.$el : gridValue);
  if (grid) {
    performanceMonitor = createHRPerformanceMonitor(grid, (state) => {
      performanceState.value = state;
    });
    workspaceController = createHRWorkspaceController(grid, initialWorkspace, () => {
      workspaceStatus.value = 'Unsaved changes';
    });
  }
  loadData();
});

onBeforeUnmount(() => {
  activeController?.abort();
  performanceMonitor?.destroy();
  workspaceController?.destroy();
  disconnectTheme?.();
});
</script>
