// pro-filtering/src/filtering.vue
<template>
  <section class="order-explorer" aria-label="Advanced Filtering: Order Explorer">
    <div class="order-explorer__toolbar">
      <div class="order-explorer__presets" aria-label="Filter presets">
        <p class="order-explorer__eyebrow">Presets</p>
        <button class="rv-btn" type="button" @click="applyPreset('high-value-europe')">High-value Europe</button>
        <button class="rv-btn" type="button" @click="applyPreset('recent-expedited')">Recent expedited</button>
        <button class="rv-btn" type="button" @click="applyPreset('review-queue')">Review queue</button>
      </div>
      <div class="order-explorer__summary">
        <span class="order-explorer__count" aria-live="polite">
          {{ visibleCount.toLocaleString() }} of {{ source.length.toLocaleString() }} orders
        </span>
        <button class="rv-btn-secondary" type="button" @click="applyFilterItems({})">Clear All</button>
      </div>
    </div>
    <div ref="badgesRef"></div>
    <div class="order-explorer__grid">
      <RevoGrid
        ref="gridRef"
        class="h-full w-full"
        :theme="isDark ? 'darkMaterial' : 'material'"
        :columns="columns"
        :source="source"
        :plugins="plugins"
        :column-types="columnTypes"
        :filter="filter"
        stretch="all"
        hide-attribution
        readonly
        resize
        @afterfilterapply="syncFilterState"
      />
    </div>
  </section>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import type { MultiFilterItem } from '@revolist/revogrid';
import RevoGrid from '@revolist/vue3-datagrid';
import { currentTheme, observeCurrentTheme } from '../../composables/useRandomData';
import {
  createOrderExplorerColumns,
  createOrderExplorerColumnTypes,
  createOrderExplorerFilter,
  createOrderExplorerInitialFilters,
  createOrderExplorerPreset,
  createOrderExplorerRows,
  getOrderExplorerVisibleCount,
  mountOrderExplorerFilterBadges,
  orderExplorerPlugins,
  type OrderExplorerPreset,
} from './filtering.shared';
import type { GridFilterBadgesController } from './filter-badges';
import './filtering.scss';

const isDark = ref(currentTheme().isDark());
const gridRef = ref<any>(null);
const badgesRef = ref<HTMLElement | null>(null);
const source = ref(createOrderExplorerRows());
const columns = ref(createOrderExplorerColumns());
const filter = ref(createOrderExplorerFilter(createOrderExplorerInitialFilters()));
const visibleCount = ref(source.value.length);
const plugins = [...orderExplorerPlugins];
const columnTypes = createOrderExplorerColumnTypes();
let badges: GridFilterBadgesController | undefined;
let destroyed = false;
let disconnectTheme: (() => void) | undefined;

function getGrid(): HTMLRevoGridElement | undefined {
  return gridRef.value?.$el ?? gridRef.value;
}

function applyFilterItems(items: MultiFilterItem) {
  filter.value = createOrderExplorerFilter(items);
  const grid = getGrid();
  if (grid) grid.filter = filter.value;
}

function applyPreset(preset: OrderExplorerPreset) {
  applyFilterItems(createOrderExplorerPreset(preset));
}

async function syncFilterState() {
  visibleCount.value = await getOrderExplorerVisibleCount(getGrid(), source.value.length);
}

onMounted(async () => {
  disconnectTheme = observeCurrentTheme(value => {
    isDark.value = value;
  });
  const grid = getGrid();
  if (grid && badgesRef.value) {
    const controller = await mountOrderExplorerFilterBadges(grid, badgesRef.value);
    if (destroyed) controller.destroy();
    else badges = controller;
  }
  visibleCount.value = await getOrderExplorerVisibleCount(grid, source.value.length);
});

onUnmounted(() => {
  destroyed = true;
  disconnectTheme?.();
  badges?.destroy();
});
</script>

// pro-filtering/src/filtering.react.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { MultiFilterItem } from '@revolist/revogrid';
import { RevoGrid } from '@revolist/react-datagrid';
import { currentTheme } from '../../composables/useRandomData';
import {
  createOrderExplorerColumns,
  createOrderExplorerColumnTypes,
  createOrderExplorerFilter,
  createOrderExplorerInitialFilters,
  createOrderExplorerPreset,
  createOrderExplorerRows,
  getOrderExplorerVisibleCount,
  mountOrderExplorerFilterBadges,
  orderExplorerPlugins,
  type OrderExplorerPreset,
  type OrderExplorerRow,
} from './filtering.shared';
import './filtering.scss';

export default function Filtering({ rows }: { rows?: OrderExplorerRow[] }) {
  const { isDark } = currentTheme();
  const gridRef = useRef<HTMLRevoGridElement>(null);
  const badgesRef = useRef<HTMLDivElement>(null);
  const source = useMemo(() => rows?.length ? rows : createOrderExplorerRows(), [rows]);
  const columns = useMemo(() => createOrderExplorerColumns(), []);
  const plugins = useMemo(() => [...orderExplorerPlugins], []);
  const columnTypes = useMemo(() => createOrderExplorerColumnTypes(), []);
  const [filter, setFilter] = useState(() => createOrderExplorerFilter(createOrderExplorerInitialFilters()));
  const [visibleCount, setVisibleCount] = useState(source.length);

  const applyFilterItems = useCallback((items: MultiFilterItem) => {
    const nextFilter = createOrderExplorerFilter(items);
    setFilter(nextFilter);
    if (gridRef.current) gridRef.current.filter = nextFilter;
  }, []);

  const applyPreset = (preset: OrderExplorerPreset) => {
    applyFilterItems(createOrderExplorerPreset(preset));
  };

  useEffect(() => {
    const grid = gridRef.current;
    const badgesRoot = badgesRef.current;
    if (!grid || !badgesRoot) return;
    let destroyed = false;
    let badges: Awaited<ReturnType<typeof mountOrderExplorerFilterBadges>> | undefined;
    const syncFilterState = async () => {
      setVisibleCount(await getOrderExplorerVisibleCount(grid, source.length));
    };
    grid.addEventListener('afterfilterapply', syncFilterState);
    void mountOrderExplorerFilterBadges(grid, badgesRoot).then(controller => {
      if (destroyed) controller.destroy();
      else badges = controller;
    });
    void getOrderExplorerVisibleCount(grid, source.length).then(setVisibleCount);
    return () => {
      destroyed = true;
      badges?.destroy();
      grid.removeEventListener('afterfilterapply', syncFilterState);
    };
  }, [source.length]);

  return (
    <section className="order-explorer" aria-label="Advanced Filtering: Order Explorer">
      <div className="order-explorer__toolbar">
        <div className="order-explorer__presets" aria-label="Filter presets">
          <p className="order-explorer__eyebrow">Presets</p>
          <button className="rv-btn" type="button" onClick={() => applyPreset('high-value-europe')}>High-value Europe</button>
          <button className="rv-btn" type="button" onClick={() => applyPreset('recent-expedited')}>Recent expedited</button>
          <button className="rv-btn" type="button" onClick={() => applyPreset('review-queue')}>Review queue</button>
        </div>
        <div className="order-explorer__summary">
          <span className="order-explorer__count" aria-live="polite">
            {visibleCount.toLocaleString()} of {source.length.toLocaleString()} orders
          </span>
          <button className="rv-btn-secondary" type="button" onClick={() => applyFilterItems({})}>Clear All</button>
        </div>
      </div>
      <div ref={badgesRef}></div>
      <div className="order-explorer__grid">
        <RevoGrid
          ref={gridRef}
          className="h-full w-full"
          theme={isDark() ? 'darkMaterial' : 'material'}
          columns={columns}
          source={source}
          plugins={plugins}
          columnTypes={columnTypes}
          filter={filter}
          stretch="all"
          hideAttribution={true}
          readonly={true}
          resize={true}
        />
      </div>
    </section>
  );
}
