// pro-filtering/src/remote.vue
<template><div ref="root" class="remote-filter-recipe"></div></template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue';
import { mountRemoteFilteringRecipe } from './remote.shared';

const root = ref<HTMLElement | null>(null);
let cleanup: (() => void) | undefined;
onMounted(() => { if (root.value) cleanup = mountRemoteFilteringRecipe(root.value); });
onUnmounted(() => cleanup?.());
</script>

// pro-filtering/src/remote.react.tsx
import { useEffect, useRef } from 'react';
import { mountRemoteFilteringRecipe } from './remote.shared';

export default function RemoteFilteringRecipe() {
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => root.current ? mountRemoteFilteringRecipe(root.current) : undefined, []);
  return <div ref={root} className="remote-filter-recipe" />;
}
