// pro-column-collapse/src/column-collapse.vue
<template>
  <section class="column-collapse-showcase" aria-label="Column Collapse contact workspace">
    <div class="column-collapse-toolbar">
      <div>
        <strong>Contact workspace</strong>
        <span>Collapse a grouped header to keep only its sealed column visible.</span>
      </div>
      <div class="column-collapse-legend" aria-label="Column collapse legend">
        <span><i class="column-collapse-dot column-collapse-dot--sealed"></i>Sealed</span>
        <span><i class="column-collapse-dot column-collapse-dot--hidden"></i>Collapsible</span>
      </div>
    </div>
    <RevoGrid
      class="column-collapse-grid"
      :theme="darkTheme ? 'darkMaterial' : 'material'"
      :columns="columns"
      :source="rows"
      :plugins="plugins"
      :row-headers="true"
      :resize="true"
      hide-attribution
    />
  </section>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import RevoGrid from '@revolist/vue3-datagrid';
import {
  AdvanceFilterPlugin,
  ColumnCollapsePlugin,
  FilterHeaderPlugin,
  RowOddPlugin,
  RowSelectPlugin,
} from '@revolist/revogrid-pro';
import {
  createColumnCollapseColumns,
  createColumnCollapseRows,
  prefersDarkTheme,
  type ContactRow,
} from './column-collapse.shared';
import './column-collapse.scss';

const props = defineProps<{ rows?: ContactRow[] }>();
const rows = ref(props.rows?.length ? props.rows : createColumnCollapseRows());
const columns = createColumnCollapseColumns();
const plugins = [ColumnCollapsePlugin, AdvanceFilterPlugin, FilterHeaderPlugin, RowSelectPlugin, RowOddPlugin];
const darkTheme = ref(prefersDarkTheme());
</script>

// pro-column-collapse/src/column-collapse.react.tsx
import { useMemo } from 'react';
import { RevoGrid } from '@revolist/react-datagrid';
import {
  AdvanceFilterPlugin,
  ColumnCollapsePlugin,
  FilterHeaderPlugin,
  RowOddPlugin,
  RowSelectPlugin,
} from '@revolist/revogrid-pro';
import {
  createColumnCollapseColumns,
  createColumnCollapseRows,
  prefersDarkTheme,
  type ContactRow,
} from './column-collapse.shared';
import './column-collapse.scss';

export default function ColumnCollapse({ rows }: { rows?: ContactRow[] }) {
  const source = useMemo(() => rows?.length ? rows : createColumnCollapseRows(), [rows]);
  const columns = useMemo(() => createColumnCollapseColumns(), []);
  const plugins = useMemo(() => [
    ColumnCollapsePlugin,
    AdvanceFilterPlugin,
    FilterHeaderPlugin,
    RowSelectPlugin,
    RowOddPlugin,
  ], []);

  return (
    <section className="column-collapse-showcase" aria-label="Column Collapse contact workspace">
      <div className="column-collapse-toolbar">
        <div>
          <strong>Contact workspace</strong>
          <span>Collapse a grouped header to keep only its sealed column visible.</span>
        </div>
        <div className="column-collapse-legend" aria-label="Column collapse legend">
          <span><i className="column-collapse-dot column-collapse-dot--sealed" />Sealed</span>
          <span><i className="column-collapse-dot column-collapse-dot--hidden" />Collapsible</span>
        </div>
      </div>
      <RevoGrid
        className="column-collapse-grid"
        theme={prefersDarkTheme() ? 'darkMaterial' : 'material'}
        columns={columns}
        source={source}
        plugins={plugins}
        rowHeaders={true}
        resize={true}
        hideAttribution={true}
      />
    </section>
  );
}
