// pro-e-commerce/src/ecommerce.vue
// src/components/showcase/ECommerce.vue

<template>
  <div class="ecommerce-shell grow">
    <div class="ecommerce-toolbar">
      <div class="ecommerce-toolbar__main">
        <span class="ecommerce-chip">
          <span>Rows</span>
          <strong>{{ rowsCountLabel }}</strong>
        </span>
        <label class="ecommerce-filter">
          <span aria-hidden="true">⌕</span>
          <textarea
            v-model="filterExpression"
            rows="1"
            placeholder='Gender eq "Female" and City eq "Chicago"'
          ></textarea>
        </label>
      </div>

      <div class="ecommerce-toolbar__aside">
        <span class="ecommerce-chip">
          <span>Spend</span>
          <strong>{{ totalSpend }}</strong>
        </span>
        <button
          type="button"
          class="ecommerce-button ecommerce-button--export"
          @click="exportToExcel"
        >
          Export
        </button>
      </div>
    </div>

    <RevoGrid
      class="ecommerce-grid skip-style cell-border"
      range
      ref="grid"
      :theme="isDark.value ? 'darkMaterial' : 'material'"
      :columns="visibleColumns"
      :source="visibleRows"
      :plugins="plugins"
      :row-context-menu.prop="contextMenus.rowContextMenu"
      :column-context-menu.prop="contextMenus.columnContextMenu"
      stretch="last"
      :column-types="columnTypes"
      :filter="ecommerceFilterConfig"
      :hide-columns="hiddenColumns"
      style="min-height: 0"
      resize
      hide-attribution
      @rowselected="handleRowSelected"
    />
  </div>
</template>

<script setup lang="ts">
import './ecommerce.scss';
import { currentThemeVue } from '../../composables/useRandomData';
import RevoGrid from '@revolist/vue3-datagrid';
import type {
  ColumnProp,
  ColumnGrouping,
  ColumnRegular,
} from '@revolist/revogrid';
import {
  ExportExcelPlugin,
} from '@revolist/revogrid-pro';
import {
  createEcommerceAnalyticsColumns,
  createEcommerceContextMenus,
  createEcommerceExcelExportConfig,
  clearEcommerceSelection,
  ecommerceColumnTypes,
  ecommerceFilterConfig,
  ecommercePlugins,
  filterEcommerceRows,
  formatEcommerceTotalSpend,
  getSelectedEcommerceIndexes,
  getVisibleEcommerceColumns,
  normalizeEcommerceRows,
} from './ecommerce.shared';
import { computed, ref, shallowRef, watch } from 'vue';

const props = defineProps({
  rows: {
    type: Array<any>,
    default: () => [],
  },
});

const grid = ref<{ $el: HTMLRevoGridElement } | null>(null);
const columnTypes = ecommerceColumnTypes;
const columns = ref<(ColumnRegular | ColumnGrouping)[]>(createEcommerceAnalyticsColumns());
const plugins = ecommercePlugins;
const hiddenColumns = ref<ColumnProp[]>([]);
const localRows = ref<any[]>([]);
const selectedIndexes = shallowRef<Set<number>>(new Set());

const { isDark } = currentThemeVue();

const exportToExcel = async () => {
  if (grid.value) {
    const plugins = await grid.value.$el.getPlugins();
    const exportPlugin = plugins.find(
      (plugin) => plugin instanceof ExportExcelPlugin,
    ) as ExportExcelPlugin;
    exportPlugin?.export(createEcommerceExcelExportConfig());
  }
};

const resetSelection = () => {
  selectedIndexes.value = new Set();
  selectedRowsCount.value = 0;
  clearEcommerceSelection(grid.value?.$el);
};

const contextMenus = computed(() => createEcommerceContextMenus({
  getRows: () => localRows.value,
  setRows: (rows) => {
    localRows.value = rows;
    allRowsCount.value = rows.length;
  },
  getColumns: () => columns.value,
  setColumns: (nextColumns) => {
    columns.value = nextColumns;
  },
  getHiddenColumns: () => hiddenColumns.value,
  setHiddenColumns: (nextHiddenColumns) => {
    hiddenColumns.value = nextHiddenColumns;
  },
  getGrid: () => grid.value?.$el,
  getSelectedIndexes: () => selectedIndexes.value,
  clearSelection: resetSelection,
  exportExcel: exportToExcel,
}));

const filterExpression = ref('');

const selectedRowsCount = ref(0);
const allRowsCount = ref(0);
watch(
  () => props.rows.length,
  () => {
    allRowsCount.value = props.rows.length;
  },
  { immediate: true },
);

watch(
  () => props.rows,
  (nextRows) => {
    localRows.value = normalizeEcommerceRows(nextRows);
  },
  { immediate: true },
);

const visibleRows = computed(() => filterEcommerceRows(localRows.value, filterExpression.value));
const visibleRowsCount = computed(() => visibleRows.value.length);
const rowsCountLabel = computed(() =>
  selectedRowsCount.value === allRowsCount.value
    ? String(allRowsCount.value)
    : `${selectedRowsCount.value}/${allRowsCount.value}`,
);

const totalSpend = computed(() => {
  return formatEcommerceTotalSpend(visibleRows.value);
});

const handleRowSelected = (
  event: CustomEvent<HTMLRevoGridElementEventMap['rowselected']>,
) => {
  selectedIndexes.value = getSelectedEcommerceIndexes(event, localRows.value);
  selectedRowsCount.value = event.detail.count;
  allRowsCount.value = event.detail.allRowsCount;
};

const visibleColumns = computed(() =>
  getVisibleEcommerceColumns(columns.value, hiddenColumns.value),
);
</script>

// pro-e-commerce/src/ecommerce.react.tsx
// src/components/showcase/ECommerce.tsx

import './ecommerce.scss';
import React, { useCallback, useEffect, useState, useMemo, useRef } from 'react';
import {
  RevoGrid,
  type DataType,
} from '@revolist/react-datagrid';
import type { ColumnProp } from '@revolist/revogrid';
import { ExportExcelPlugin } from '@revolist/revogrid-pro';
import { currentTheme } from '../../composables/useRandomData';
import {
  createEcommerceAnalyticsColumns,
  createEcommerceContextMenus,
  createEcommerceExcelExportConfig,
  clearEcommerceSelection,
  ecommerceColumnTypes,
  ecommerceFilterConfig,
  ecommercePlugins,
  filterEcommerceRows,
  formatEcommerceTotalSpend,
  getSelectedEcommerceIndexes,
  getVisibleEcommerceColumns,
  normalizeEcommerceRows,
} from './ecommerce.shared';

interface ECommerceProps {
  rows?: DataType[];
  fields?: string[];
}

function ECommerce({ rows = [], fields = [] }: ECommerceProps) {
  const gridRef = useRef<HTMLRevoGridElement>(null);
  const [filterExpression, setFilterExpression] = useState('');
  const [hiddenColumns, setHiddenColumns] = useState<ColumnProp[]>([]);
  const [selectedRowsCount, setSelectedRowsCount] = useState(0);
  const [selectedIndexes, setSelectedIndexes] = useState<Set<number>>(() => new Set());
  const [allRowsCount, setAllRowsCount] = useState(0);

  const { isDark } = currentTheme();

  const theme = isDark() ? 'darkMaterial' : 'material';

  const [columns, setColumns] = useState(createEcommerceAnalyticsColumns);
  const [source, setSource] = useState(() => normalizeEcommerceRows(rows));

  const columnTypes = useMemo(() => ecommerceColumnTypes, []);
  const plugins = useMemo(() => ecommercePlugins, []);
  const visibleColumns = useMemo(
    () => getVisibleEcommerceColumns(columns, hiddenColumns),
    [columns, hiddenColumns],
  );
  const visibleRows = useMemo(
    () => filterEcommerceRows(source, filterExpression),
    [source, filterExpression],
  );
  const totalSpend = useMemo(
    () => formatEcommerceTotalSpend(visibleRows),
    [visibleRows],
  );
  const totalRowsCount = allRowsCount || source.length;
  const rowsCountLabel = selectedRowsCount === totalRowsCount
    ? String(totalRowsCount)
    : `${selectedRowsCount}/${totalRowsCount}`;

  useEffect(() => {
    setSource(normalizeEcommerceRows(rows));
  }, [rows]);

  const exportToExcel = async () => {
    const grid = gridRef.current;
    if (grid) {
      const plugins = await grid.getPlugins();
      const exportPlugin = plugins.find(
        (plugin) => plugin instanceof ExportExcelPlugin,
      ) as ExportExcelPlugin;
      exportPlugin?.export(createEcommerceExcelExportConfig());
    }
  };

  const resetSelection = useCallback(() => {
    setSelectedIndexes(new Set());
    setSelectedRowsCount(0);
    clearEcommerceSelection(gridRef.current);
  }, []);

  const contextMenus = useMemo(() => createEcommerceContextMenus({
    getRows: () => source,
    setRows: (nextRows) => {
      setSource(nextRows);
      setAllRowsCount(nextRows.length);
    },
    getColumns: () => columns,
    setColumns: (nextColumns) => setColumns(nextColumns),
    getHiddenColumns: () => hiddenColumns,
    setHiddenColumns,
    getGrid: () => gridRef.current,
    getSelectedIndexes: () => selectedIndexes,
    clearSelection: resetSelection,
    exportExcel: exportToExcel,
  }), [columns, hiddenColumns, resetSelection, selectedIndexes, source]);

  const handleRowSelected = (
    event: CustomEvent<HTMLRevoGridElementEventMap['rowselected']>,
  ) => {
    setSelectedIndexes(getSelectedEcommerceIndexes(event, source));
    setSelectedRowsCount(event.detail.count);
    setAllRowsCount(event.detail.allRowsCount || source.length);
  };

  return (
    <div className="ecommerce-shell grow">
      <div className="ecommerce-toolbar">
        <div className="ecommerce-toolbar__main">
          <span className="ecommerce-chip">
            <span>Rows</span>
            <strong>{rowsCountLabel}</strong>
          </span>
          <label className="ecommerce-filter">
            <span aria-hidden="true">⌕</span>
            <textarea
              id="filterExpression"
              rows={1}
              placeholder='Gender eq "Female" and City eq "Chicago"'
              value={filterExpression}
              onChange={(e) => setFilterExpression(e.target.value)}
            />
          </label>
        </div>
        <div className="ecommerce-toolbar__aside">
          <span className="ecommerce-chip">
            <span>Spend</span>
            <strong>{totalSpend}</strong>
          </span>
          <button
            type="button"
            className="ecommerce-button ecommerce-button--export"
            onClick={exportToExcel}
          >
            Export
          </button>
        </div>
      </div>
      <RevoGrid
        className="ecommerce-grid skip-style cell-border"
        range
        ref={gridRef}
        columns={visibleColumns}
        source={visibleRows}
        plugins={plugins}
        columnTypes={columnTypes}
        rowContextMenu={contextMenus.rowContextMenu}
        columnContextMenu={contextMenus.columnContextMenu}
        filter={ecommerceFilterConfig}
        hideColumns={hiddenColumns}
        stretch="last"
        resize
        hide-attribution
        theme={theme}
        onRowselected={handleRowSelected}
      />
    </div>
  );
}

export default ECommerce;
